spline	:	sbart.c bsplvd.f bvalue.f sgram.f sslvrg.f stxwx.f
	gcc -I /usr/include/R/ -c fuck.c
	gfortran -c bsplvd.f bvalue.f bvalus.f sgram.f sinerp.f sslvrg.f stxwx.f
	gcc bsplvd.o bvalue.o bvalus.o fuck.o sgram.o sinerp.o sslvrg.o stxwx.o -L/usr/lib/R/lib/ -lR -lblas -lgfortran -lm
